Added a new lab about change data capture using DynamoDB streams and Kinesis data streams.
aws-samples/amazon-dynamodb-labs pull request #101
Opened 2023-12-19 16:17 UTC by iojior

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-05 20:16 UTC, tebanieo requested changes
Hello

Thanks for your patience and for the PR.

Most of the changes that I suggested are intended to increase readibility.

There are a few that are important, specially in terms of lambda code and some references in the sections.

Enhancement suggestion: Add DLQ to your lambdas to process errors.

2024-02-05 20:16 UTC, tebanieo commented on content/change-data-capture/ex1/simulate-order-updates.en.md
> +::alert[_The order of updates to the Orders table is preserved by DynamoDB streams when changes are sent to the create order history lambda function. Hence, items on the OrdersHistory table can be so
You forgot to mention about the `sk`

2024-02-05 20:16 UTC, tebanieo commented on content/change-data-capture/ex2/index.en.md
> +Amazon Kinesis Data Streams can be used to collect and process large streams of data records from applications that produce streaming data in real-time. At a high level, data producers push data reco
Insert Hyperlink https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/kds.html

2024-02-05 20:16 UTC, tebanieo commented on content/change-data-capture/ex2/enable-kds-streams.en.md
> +Create a Kinesis data stream named **Orders** using the following command.
`Orders`

2024-02-05 20:16 UTC, tebanieo commented on content/change-data-capture/ex2/create-lambda.en.md
> +    store_history_record(data["dynamodb"]["OldImage"])
This is not null safe.

2024-02-05 20:16 UTC, tebanieo commented on content/change-data-capture/ex2/create-lambda.en.md
> +![AWS Lambda function creation wizard](/static/images/change-data-capture/ex1/deploy-code.png)
Please update the picture, this one is pointing to the DynamoDB streams example, Customers can get confused by this.

2024-02-05 20:16 UTC, tebanieo commented on content/change-data-capture/ex2/simulate-order-updates.en.md
> +title: "Simulate Order Updates"
Same comment than in the Streams Labs, you ask the customer to see the console but then you ask them to run the examples in the CLI. If you want them to learn about this experience you should show them how to do both. 

Please add a note that now the integration with KDS can ad the timestamp 

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/kds.html#kds_howitworks

```
When you enable a Kinesis data stream as a streaming destination of a DynamoDB table, you can configure the precision of ApproximateCreationDateTime values in either milliseconds or microseconds. By default, ApproximateCreationDateTime indicates the time of the change in milliseconds. Additionally, you can change this value on an active streaming destination. After such an update, stream records written to Kinesis will have ApproximateCreationDateTime values of the desired precision
```

2024-02-05 20:16 UTC, tebanieo commented on content/change-data-capture/setup/user-account.en.md
> +
Add a comment that you need a role that have rights to Create and Delete:  Lambda, DynamoDB Tables, roles, lambda triggers, kinesis data streams and Dynamodb streams

2024-02-07 15:14 UTC, iojior commented on content/change-data-capture/overview/index.en.md
> +Orders placed on your website can have one of the follow statuses - `ACTIVE`, `PLACED`, `COMPLETE` or `CANCELLED`; but you only want to keep the current view of customers' orders on the main database
Section re-formatted. Thanks.

2024-02-07 15:47 UTC, iojior commented on content/change-data-capture/overview/prereqs.en.md
> +#### Using your own AWS account
Moved this information to the getting started section and removed the prerequisites page. Good spot. Thanks.

2024-02-07 16:17 UTC, iojior commented on content/change-data-capture/overview/create-tables.en.md
> +Copy the **create-table** commands below and paste them into your command terminal. Execute the commands to to create two tables named Orders and OrdersHistory.
Additional explanation added. Thanks.

2024-02-07 22:27 UTC, iojior commented on content/change-data-capture/ex1/index.en.md
> +![Final Deployment Architecture](/static/images/change-data-capture/cdc-ddbs/create-order-history-ddbs.png)
Thanks. I don't understand this part "_the arrow between orders and lambda should be the trigger and the arrow between the lambda and the OrdersHistory table should be the write item_". There isn't a trigger icon or a write item icon. Can you elaborate please?

2024-02-07 23:33 UTC, iojior commented on content/change-data-capture/ex1/create-lambda.en.md
> +            store_history_record(record.dynamodb.old_image)
Since the if statement is checking specifically for modified records, and the stream only holds old images, I don't think we can end up with a null record here. I can update the if check to include deleted records (i.e. _DynamoDBRecordEventName.REMOVE_) but I figured that this is not necessary to illustrate the streamed records being processed. Do you agree?

2024-02-07 23:48 UTC, iojior commented on content/change-data-capture/ex1/simulate-order-updates.en.md
> +Copy the JSON data below into a file called **6421680-items.json**.
Thanks for pointing this out. The Hands-on Labs for Amazon DynamoDB workshops has a section that takes the user through the console and explains how to perform item updates via the console. i.e. https://catalog.workshops.aws/dynamodb-labs/en-US/hands-on-labs/explore-console/console-writing-data

By getting the user to perform the update using the CLI, I am trying to show a different technique for completing updates to DynamoDB tables. I intentionally did not call this out explicitly.

Would you prefer it if I add a note saying the user could look at page https://catalog.workshops.aws/dynamodb-labs/en-US/hands-on-labs/explore-console/console-writing-data it they require a refresher for completing item updates via the console? Or would you like me to walk the user through performing the task using the AWS Management console?

2024-02-08 00:25 UTC, iojior commented on content/change-data-capture/ex2/simulate-order-updates.en.md
> +title: "Simulate Order Updates"
Thanks for the information. Updated.

2024-02-12 10:53 UTC, iojior commented on content/change-data-capture/ex2/create-lambda.en.md
> +    store_history_record(data["dynamodb"]["OldImage"])
Updated to make it null safe. Thanks.

2024-02-21 23:53 UTC, tebanieo commented on content/change-data-capture/ex1/index.en.md
> +![Final Deployment Architecture](/static/images/change-data-capture/cdc-ddbs/create-order-history-ddbs.png)
Its ok, I am happy with the Streams change, we can ignore the rest

2024-02-22 00:00 UTC, tebanieo commented on content/change-data-capture/ex1/create-lambda.en.md
> +            store_history_record(record.dynamodb.old_image)
You are correct, however you are assuming the user will do exactly as you said, which is usually not the case. 

What if the customer decides to use different partition keys? "PK" instead of "pk"? Users will always change the code, and itis better to handle that gracefully showing in the logs what you got, instead of having an exception. 

The comment was more on the format of the message then the conditional itself.

2024-02-22 00:03 UTC, tebanieo commented on content/change-data-capture/ex1/simulate-order-updates.en.md
> +Copy the JSON data below into a file called **6421680-items.json**.
Please at least add the note. I personally think creating the JSON file is an unnecessary overhead.

2024-02-22 00:12 UTC, tebanieo commented
Thanks for fixing the comments, I saw the new files they look good to me, fix the missing 3 comments to proceed. Also there has been some updates in the master branch, please rebase your branch and push the updated values.

2024-02-28 14:38 UTC, iojior commented on content/change-data-capture/ex1/create-lambda.en.md
> +            store_history_record(record.dynamodb.old_image)
Thanks @tebanieo. I've put in a check to ensure that the expected key is present before the stream record is processed.

2024-02-28 20:15 UTC, tebanieo approved these changes

2024-02-28 20:16 UTC, merged