Opensearch lab
aws-samples/amazon-dynamodb-labs pull request #107
Opened 2024-02-25 23:17 UTC by terhunej

*Issue #, if available:*

*Description of changes:*
Added new lab for DynamoDB zero-ETL to OpenSearch integration.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-28 20:42 UTC, tebanieo requested changes
Hello, This lab looks very nice. I have added a couple of comments on the CloudFormation file and the minor formatting of the pictures, please ensure you add an extra "Enter" between pictures so the lab looks less cluttered.

2024-02-28 20:42 UTC, tebanieo commented on content/hands-on-labs/dynamodb-opensearch-zetl/ddb-os-zetl-chapter02.en.md
> + 1. Launch the CloudFormation template in US West 2 to deploy the resources in your account: [![CloudFormation](/static/images/cloudformation-launch-stack.png)](https://console.aws.amazon.com/cloudfo
Please add a "Enter" before the pictures. In the current build the images are cluttered with the text. (the same comment goes for all the pictures in this PR).

2024-02-28 20:42 UTC, tebanieo commented on static/files/hands-on-labs/dynamodb-opensearch-setup.yaml
> +    Default: "nyz@5k%Ty&KUEG5@"
If I put my security reviewer hat, this password needs to go in secrets manager.  `nice-to-have` I will also auto generate a password for every deployment.

2024-02-28 20:42 UTC, tebanieo commented on static/files/hands-on-labs/dynamodb-opensearch-setup.yaml
> +            Action: 'es:*'
Overpermissive policy, If this is intended please ignore. But I feel this can be reduced to only some actions. In the lab there are not many actions executed with the cluster.

2024-02-28 20:42 UTC, tebanieo commented on static/files/hands-on-labs/dynamodb-opensearch-setup.yaml
> +  OSMasterUserPassword:
Secrets manager instead?

2024-02-28 20:42 UTC, tebanieo commented on static/files/hands-on-labs/dynamodb-opensearch-setup.yaml
> +        MasterUserOptions:
Get this info from Secrets Manager?

2024-02-28 20:42 UTC, tebanieo commented on content/hands-on-labs/dynamodb-opensearch-zetl/ddb-os-zetl-chapter08.en.md
> + 1. In the console, execute the provided python script to make a query to Bedrock and return product results.
This section is very light. Users are running this lab in order to grasp the script's result, but there is no explanation provided regarding the functionality of the Python script or the events that unfolded. Consider adding more context and information on this.

2024-02-28 20:42 UTC, tebanieo commented on static/images/ddb-os-zetl7.jpg
this picture don't show the results of the query, maybe it is a typo on the file name?

2024-02-28 20:43 UTC, tebanieo commented
Oh, please rebase this branch as there were additional deployments. Thanks!

2024-03-01 09:49 UTC, amdhing commented
In addition to @tebanieo comments could you also add 
1/ A warning note on the first page of the lab with a list of AWS services that will be used as part of this lab and an approximate of costs that may be incurred ("10s to 100s of dollars per day" will do if appropriate) if the reader were following the lab in their own AWS accounts (and not AWS provided lab accounts).

2/ A warning note on the final "Query and Conclusion" page reminding reader to delete the CFN stack and resources created as part of the lab if they were following it in their own AWS accounts. Can refer to https://catalog.workshops.aws/dynamodb-labs/en-US/game-player-data/summary for the same.

Thanks!

2024-03-16 07:19 UTC, terhunej commented on static/files/hands-on-labs/dynamodb-opensearch-setup.yaml
> +            Action: 'es:*'
Currently this resource policy doesn't provide any additional permissions than the Cloud9Role already has through an identity policy. I'll open an issue to rework it as part of a larger effort to tune policies to least privilege.

2024-03-21 19:35 UTC, switch180 commented on contentspec.yaml
> +  lhol_ddb_os_zetl_setup_yaml : "https://s3.amazonaws.com/amazon-dynamodb-labs.com/assets/dynamodb-opensearch-setup.yaml"
Pushed to WS repo in commit d74a2a4. This means that this reference is locked in, and needs to be manually updated in the WS contentspec if the path is changed.

2024-03-21 19:43 UTC, switch180 requested changes
I have reviewed this lab from a deployment perspective. I have prepared this lab for merge, pending approval. It will build the OS pipeline ZIP and copy it to S3 on deploy. 

Please review my comment and provide guidance on the origins of the bedrock_query.py script.

Once all changes are complete and this is ready, I will squash merge and then push it to the lab guide in WS.

2024-03-21 19:43 UTC, switch180 commented on static/files/hands-on-labs/OpenSearchPipeline/bedrock_query.py
> +    # 构建bedrock与 es客户端
I pulled this script out of the code ZIP and into a top level file. Please let me know if this is a problem. On deploy it will build into a ZIP.

Upon review I see this has Chinese in it. Can you please attest to the license of the code and whether it passes the open source policies for use? If this is Amazon-owned code, please add the comments on top with the license like [you see here](https://github.com/aws-samples/amazon-dynamodb-labs/blob/c0c3669856becce1d6c50e7e8cfbbfe6d87e8973/event-driven/MapLambdaPackage/lambda_function.py#L4)

2024-03-22 14:53 UTC, tebanieo approved these changes

2024-03-22 20:56 UTC, switch180 approved these changes

2024-03-22 21:06 UTC, switch180 commented
Testing on WS now...

2024-03-22 22:59 UTC, switch180 commented
Changes requested. The stack took 26 minutes to launch today. This is untenable in a hands on lab situation due to the delays and extra labor this will take. 

- [ ] Move the OS template into WS and add it to the contentspec so it is launched during provisioning. Ensure the exact same copy of the template is the one you publish in this repo - it will be rsync'd from this repo and overwrite the version in WS with each update (done manually by executing a shell script not found in source control)
- [ ] Update the lab guide in line with LHOL/LGME so it clearly explains the at-home versus at-aws-event options. This means you should more or less copy the lab guide sections from one of those labs, being sure that the hyperlinks are correct
- [ ] Resolve code comments (adding those now)

Also, I want to point out that our style guide has guidance that may affect the username that you chose. Please consider changing the username of the OS user, understanding that you will need update all related screenshots as well.

2024-03-22 23:03 UTC, switch180 requested changes

2024-03-22 23:03 UTC, switch180 commented on content/hands-on-labs/dynamodb-opensearch-zetl/ddb-os-zetl-chapter03.en.md
> +1. When prompted to select your tenant, choose *Global* and click **Confirm**. Dismiss any modals that pop up.
Is this correct? Global tenant? I added this step and photo after noticing this option was not mentioned in the guide,

2024-03-22 23:03 UTC, switch180 commented on content/hands-on-labs/dynamodb-opensearch-zetl/ddb-os-zetl-chapter07.en.md
> + 1. After the pipeline is created, it will take some additional time for the initial export from DynamoDB and import into OpenSearch Service. After you have waited several more minutes, you can check
Provide a sample query in dev-tools in copy-paste or step-by-step form. The one shown in the screenshot does not work as-is.

2024-03-22 23:03 UTC, switch180 commented on content/hands-on-labs/dynamodb-opensearch-zetl/ddb-os-zetl-chapter08.en.md
> +Congratulations! You have completed the lab.
Hey, now! This is literally the coolest part of the lab and it just ends.
I think you need to add several more queries, a list or table, so that users can play around with it!!!

2024-03-22 23:03 UTC, switch180 commented on static/files/hands-on-labs/dynamodb-opensearch-setup.yaml
> +        SecretStringTemplate: '{"username": "master-user"}'
Consider changing at your discretion.

2024-03-29 00:43 UTC, switch180 commented
Testing in WS. Running into failures unrelated to this lab. Will work on merging tomorrow.

2024-03-29 21:08 UTC, switch180 commented on static/images/ddb-os-zetl.png
Can you please check in the drawio for this diagram? If it's a PPTX nvm

2024-03-29 21:11 UTC, terhunej commented
It’s PPTX

On Fri, Mar 29, 2024 at 2:09 PM Sean Shriver ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On static/images/ddb-os-zetl.png
> <https://github.com/aws-samples/amazon-dynamodb-labs/pull/107#discussion_r1544873651>
> :
>
> Can you please check in the drawio for this diagram? If it's a PPTX nvm
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/aws-samples/amazon-dynamodb-labs/pull/107#pullrequestreview-1969608952>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACVXF3XTPYLJJ66PJE5QPO3Y2XJ6ZAVCNFSM6AAAAABDZHPIZ6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNRZGYYDQOJVGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-29 23:50 UTC, switch180 approved these changes

2024-03-29 23:51 UTC, merged