relational migration instructions initial
aws-samples/amazon-dynamodb-labs pull request #121
Opened 2024-11-13 20:01 UTC by robm26

Instructions for the new relational-migration workshop

Several readme files and static images.  No code since this is retrieved by the user with git clone from another repository. Thank you!!!

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-11-14 17:43 UTC, switch180 commented
Requested changes:
1. Use a Parameter for the MySQL password and username instead of hard coding it. Follow the [method seen here](https://github.com/aws-samples/amazon-dynamodb-labs/blob/master/static/files/hands-on-labs/migration-env-setup.yaml). Parameter at the top of the stack, referenced in the user data script
2. Pre-cache the code for the workshop on the C9 instance instead of having a git clone. [UserData script](https://github.com/aws-samples/amazon-dynamodb-labs/blob/master/design-patterns/cloudformation/UserDataC9.sh). We will talk about this.
3. Provide the license for vehicles.png so we know we have the permission to use it on our lab
4. Update the main index.en.md to explain what technologies you will use. You should list them all out, with a separate section for AWS services and code frameworks.
5. Complete your changes by Friday :-)

2024-11-15 17:38 UTC, switch180 requested changes
Feedback added on C9.yaml - please address the line comments

2024-11-15 17:38 UTC, switch180 commented on design-patterns/cloudformation/C9.yaml
> +  MigrationS3Bucket:
How does the S3 bucket get identified for use in the workshop? Is this in one of your scripts? Does it look for the CFN stack and grab the Output you made for the S3 bucket?

2024-11-15 17:38 UTC, switch180 commented on design-patterns/cloudformation/C9.yaml
> +            VolumeSize: 200
Does it have to be 200 GB??

2024-11-15 17:38 UTC, switch180 commented on design-patterns/cloudformation/C9.yaml
> +          export DbMasterUsername=dbuser
Fix: should be parameter

2024-11-15 17:38 UTC, switch180 commented on design-patterns/cloudformation/C9.yaml
> +  S3Bucket:
We make another S3 bucket? What's this one used for?

2024-11-15 17:38 UTC, switch180 commented on design-patterns/cloudformation/C9.yaml
> +        - CidrIp: 172.31.0.0/16
Fix: Remove. We can use SSM if we need to get a shell on this instance

2024-11-15 17:43 UTC, robm26 commented on design-patterns/cloudformation/C9.yaml
> +  MigrationS3Bucket:
The ./setenv.sh script runs a CLI command to identify it and set it to an env var

2024-11-15 17:43 UTC, robm26 commented on design-patterns/cloudformation/C9.yaml
> +            VolumeSize: 200
How about 50 GB

2024-11-15 17:45 UTC, robm26 commented on design-patterns/cloudformation/C9.yaml
> +          export DbMasterUsername=dbuser
Updated to make DbMasterUsername a parameter value

2024-11-15 17:46 UTC, robm26 commented on design-patterns/cloudformation/C9.yaml
> +  S3Bucket:
Removed it

2024-11-15 17:47 UTC, robm26 commented on design-patterns/cloudformation/C9.yaml
> +        - CidrIp: 172.31.0.0/16
Did you mean remove the four lines starting at 743 for the port 22 access? 3306 is the MySQL port

2024-11-15 21:07 UTC, switch180 requested changes
Fix list:

- [x] Add level to introduction of lab, and say whether this can be done on your own or at an aws event. explain if it has any accompanying material such as a pptx that are unavaible to the student. and add hyperlink to folder where the code exists in the other repo
- [x] add a "on your own" and "at an aws event" setup
- [x] setenv has hard coded password and username but should get values from CFN somehow
- [x] Migrate this to the AWS DynamoDB Labs AWS account https://dynamodbworkshop.s3.amazonaws.com/migration/index.html 
- [x] Hard coded region in https://github.com/aws-samples/aws-dynamodb-examples/blob/master/workshops/relational-migration/migrate.sh
- [x] content/relational-migration/summary/index.en.md add a hyperlink to your workshop source code for DIY migrations
- [x] add required release to code samples that customers may use in production (AWS policy)
- [x] remove hard coded AWS_DEFAULT_REGION in setenv.sh
- [x] Hard code final commit version for aws-dynamodb-examples

Post launch checklist
- [ ] Review dataset and ensure we are using approved data

2024-11-15 21:07 UTC, switch180 commented on content/relational-migration/data migration/index3.en.md
> +6. Notice your import is listed along with the current status.
nit: can we add a screenshot of the import console? There's so much happening in these steps, let's get a marker so they know they've gotten to the right place

2024-11-15 21:07 UTC, switch180 commented on content/relational-migration/application refactoring/index3.en.md
> +8. Look on about line 148 for the line ```get_request['ConsistentRead'] = False```
fix: this line number will change. Find another way to get students to this line. Add a unique anchor and have them ctrl +f for it, e.g.

2024-11-15 21:07 UTC, switch180 commented on content/relational-migration/application refactoring/index3.en.md
> +10. In the terminal prompt, redeploy:  ```chalice deploy --stage dynamodb```
fix: break this out into a copyable shell-formatted command. Else I promise you, students will forget to run it

2024-11-15 22:06 UTC, switch180 commented
Patching userdata in #122

2024-11-15 23:05 UTC, robm26 commented on content/relational-migration/introduction/index.en.md
> +To further maximize the benefits of DynamoDB, these metrics should be
updated to clarify the metrics are the answers to the following questions

2024-11-15 23:06 UTC, robm26 commented on static/images/relational-migration/phases.png
I will share the PPT decks I use to make graphics

2024-11-15 23:07 UTC, robm26 commented on static/images/relational-migration/relational_schema.png
TODO

2024-11-15 23:07 UTC, robm26 commented on content/relational-migration/data migration/index3.en.md
> +    --output json --query '{"Status         ":ImportTableDescription.ImportStatus, "FailureCode    ":ImportTableDescription.FailureCode, "FailureMessage ":ImportTableDescription.FailureMessage }'
The space makes the output look pretty. It describes an Import and formats multiple columns so they are all aligned

2024-11-15 23:09 UTC, robm26 commented on content/relational-migration/application refactoring/index3.en.md
> +8. Look on about line 148 for the line ```get_request['ConsistentRead'] = False```
fixed

2024-11-15 23:09 UTC, robm26 commented on content/relational-migration/application refactoring/index3.en.md
> +10. In the terminal prompt, redeploy:  ```chalice deploy --stage dynamodb```
done

2024-11-15 23:10 UTC, robm26 commented on content/relational-migration/data migration/index3.en.md
> +6. Notice your import is listed along with the current status.
TODO

2024-11-15 23:11 UTC, robm26 commented on static/images/relational-migration/import.png
Not sure how to make it clearer? It's the JSON file that contains the table definition for a new DynamoDB table.

2024-11-15 23:18 UTC, switch180 commented on static/images/relational-migration/import.png
It doesn't make sense, though? It's just a file called TableDefinition.JSON...

What is its format? What does it do? What tool ingests it? Can I view its source because it seems important?

2024-11-15 23:18 UTC, switch180 commented
Pulling up todos from some of the line items for later follow up:
- [ ] Share MySQL WB file for this ERD [static/images/relational-migration/relational_schema.png]
- [ ] content/relational-migration/data migration/index3.en.md add image to step 6 to show import from s3

2024-11-15 23:47 UTC, robm26 commented on static/images/relational-migration/import.png
For context, this is all in the Introduction section, giving a high level preview of the workshop architecture.

Above the picture is the following text:

The Import from S3 feature requires a table definition for the new table to be created. The table definition includes details about the table including:

    Table Name
    Partition Key name and type
    Sort Key name and type (optional)
    Global Secondary Index (GSI) definitions (optional)

2024-11-16 00:28 UTC, switch180 commented on content/relational-migration/data migration/index4.en.md
> +```bash
Fix: add a banner/alert saying this command will fail if you run the previous one. Provide an alternate method to run this such as by changing the table name

2024-11-16 01:00 UTC, switch180 commented on content/relational-migration/application refactoring/index2.en.md
> +6. Notice the title of the page has updated to **DynamoDB App** in a blue color.
nit: it doesn't turn to blue on my screen. It stays red unless I force refresh

2024-11-16 01:16 UTC, robm26 commented on content/relational-migration/application refactoring/index2.en.md
> +6. Notice the title of the page has updated to **DynamoDB App** in a blue color.
Oh okay! will check. The different colors are meant to accomany the page title and document title changing.

2024-11-16 01:28 UTC, robm26 commented on static/images/relational-migration/relational-stack.png
updated. we have to ask Abishek what he was thinking to make a Public instance with fixed password!

2024-11-16 01:28 UTC, robm26 commented on content/relational-migration/data migration/index4.en.md
> +```bash
done

2024-11-16 01:55 UTC, switch180 commented on content/relational-migration/application refactoring/index2.en.md
> +6. Notice the title of the page has updated to **DynamoDB App** in a blue color.
Can't check. Need to document it now.

2024-11-16 01:57 UTC, switch180 commented on content/relational-migration/application refactoring/index2.en.md
> +6. Notice the title of the page has updated to **DynamoDB App** in a blue color.
Documented

2024-11-16 02:00 UTC, switch180 approved these changes

2024-11-16 02:09 UTC, merged