Updating notes to use "notice" and "expand" modules.
aws-samples/amazon-dynamodb-labs pull request #55
Opened 2021-08-23 05:22 UTC by tebanieo

…le and added expand for optional information

*Issue #, if available:*

*Description of changes:*
- Minor updates on description to match v2 console in setup section.
- Updated the Design Patterns pages to include Notice module instead of **Note**.
- Exercise 4, Step 3: Updated the list of available titles to be "expandable", using the same hugo module.
- Exercise 8, Step 5: Included "expandable" example when subscribing the Lambda function to DynamoDB Streams.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-23 18:18 UTC, switch180 commented on content/design-patterns/ex1capacity/Step7.en.md
> +| Attribute Name (Type) | Special Attribute?  |            Attribute Use Case             | Sample Attribute Value |
Your extra spaces in front of attribute use case have no effect on the formatting.

2021-08-23 18:19 UTC, switch180 commented on content/design-patterns/ex1capacity/Step7.en.md
> -ProvisionedThroughputExceededException: An error occurred (ProvisionedThroughputExceededException) when calling the BatchWriteItem operation (reached max retries: 9): The level of configured provisio
I'm rejecting this change. We don't want to show timing unless we have to.

2021-08-23 18:23 UTC, switch180 commented on content/design-patterns/ex4gsioverload/Step3.en.md
> +{{%expand "If you want to query other states, click here to open the list of US states with some data in the table" %}}
Nifty!

2021-08-23 18:34 UTC, switch180 requested changes
This is excellent work. You have a good attention to detail.

You include the file static/images/awsconsole3v2.png . What's the purpose of this file? I don't think it's used in the code you change.

In addition, can you undo the collapse you did on all the JSON output if what you did doesn't match the JSON output from the AWS CLI? I want it to match what the end users see.

2021-08-23 18:34 UTC, switch180 commented on content/design-patterns/ex5sparse/Step1.en.md
> -[
Why? Does the output look this way? We shouldn't collapse it if that's not what the students will see

2021-08-23 22:52 UTC, tebanieo commented on content/design-patterns/ex5sparse/Step1.en.md
> -[
I have auto-format on save activated on my Visual Studio Code, with prettier as a default formatter, this will try to collapse the json and add some extra spacing to match table format or to match some other rules I've set locally. 

Thanks for pointing this out, I will edit this file outside VS Code and commit the change so the json is not collapsed.

2021-08-23 22:56 UTC, tebanieo commented
> This is excellent work. You have a good attention to detail.
> 
> You include the file static/images/awsconsole3v2.png . What's the purpose of this file? I don't think it's used in the code you change.
> 
> In addition, can you undo the collapse you did on all the JSON output if what you did doesn't match the JSON output from the AWS CLI? I want it to match what the end users see.

Sorry this is a leftover, This is another change I am working on (in another branch). I will remove.

Thanks for the feedback I will implement the suggestions/modifications. In general all the extra spacing, re-formatting is due to my visual studio extensions and the auto format rules that I have defined locally.

Thanks!

2021-08-24 04:28 UTC, tebanieo commented on content/design-patterns/ex1capacity/Step7.en.md
> +| Attribute Name (Type) | Special Attribute?  |            Attribute Use Case             | Sample Attribute Value |
This is the auto formatting from VS code, I have prettier enabled by default, I revert the changes if required, but I believe formatting the tables help with the code readability.

2021-08-24 04:29 UTC, tebanieo commented on content/design-patterns/ex1capacity/Step7.en.md
> -ProvisionedThroughputExceededException: An error occurred (ProvisionedThroughputExceededException) when calling the BatchWriteItem operation (reached max retries: 9): The level of configured provisio
Reverted the change.

2022-05-13 22:40 UTC, merged